// TODO - implement:
//   copy
//   foreach
//   get
//   get_bool
//   get_collate
//   get_default_source
//   get_dither
//   get_double
//   get_double_with_default
//   get_duplex
//   get_finishings
//   get_int
//   get_int_with_default
//   get_length
//   get_media_type
//   get_n_copies
//   get_number_up
//   get_number_up_layout
//   get_orientation
//   get_output_bin
//   get_page_ranges
//   get_page_set
//   get_paper_height
//   get_paper_size
//   get_paper_width
//   get_print_pages
//   get_printer
//   get_printer_lpi
//   get_quality
//   get_resolution
//   get_resolution_x
//   get_resolution_y
//   get_reverse
//   get_scale
//   get_use_color
//   has_key
//   load_file
//   load_key_file
//   set
//   set_bool
//   set_collate
//   set_default_source
//   set_dither
//   set_double
//   set_duplex
//   set_finishings
//   set_int
//   set_length
//   set_media_type
//   set_n_copies
//   set_number_up
//   set_number_up_layout
//   set_orientation
//   set_output_bin
//   set_page_ranges
//   set_page_set
//   set_paper_height
//   set_paper_size
//   set_paper_width
//   set_print_pages
//   set_printer
//   set_printer_lpi
//   set_quality
//   set_resolution
//   set_resolution_xy
//   set_reverse
//   set_scale
//   set_use_color
//   to_file
//   to_gvariant
//   to_key_file
//   unset
package org.gnome.gtk

import gtk3.GtkPrintSettings
import kotlinx.cinterop.CPointer
import kotlinx.cinterop.reinterpret
import org.gnome.glib.gobject.Object

public typealias PrintSettings = CPointer<GtkPrintSettings>

public val PrintSettings.asObject: Object
  get() = reinterpret()
