// TODO - implement:
//   activate
//   add_accelerator
//   add_device_events
//   add_events
//   add_mnemonic_label
//   add_tick_callback
//   can_activate_accel
//   child_focus
//   child_notify
//   class_path
//   compute_expand
//   create_pango_context
//   create_pango_layout
//   destroy
//   destroyed
//   device_is_shadowed
//   drag_begin
//   drag_begin_with_coordinates
//   drag_check_threshold
//   drag_dest_add_image_targets
//   drag_dest_add_text_targets
//   drag_dest_add_uri_targets
//   drag_dest_find_target
//   drag_dest_get_target_list
//   drag_dest_get_track_motion
//   drag_dest_set
//   drag_dest_set_proxy
//   drag_dest_set_target_list
//   drag_dest_set_track_motion
//   drag_dest_unset
//   drag_get_data
//   drag_highlight
//   drag_source_add_image_targets
//   drag_source_add_text_targets
//   drag_source_add_uri_targets
//   drag_source_get_target_list
//   drag_source_set
//   drag_source_set_icon_gicon
//   drag_source_set_icon_name
//   drag_source_set_icon_pixbuf
//   drag_source_set_icon_stock
//   drag_source_set_target_list
//   drag_source_unset
//   drag_unhighlight
//   draw
//   ensure_style
//   error_bell
//   event
//   freeze_child_notify
//   get_accessible
//   get_action_group
//   get_allocated_baseline
//   get_allocated_height
//   get_allocated_size
//   get_allocated_width
//   get_allocation
//   get_ancestor
//   get_app_paintable
//   get_can_default
//   get_can_focus
//   get_child_requisition
//   get_child_visible
//   get_clip
//   get_clipboard
//   get_composite_name
//   get_device_enabled
//   get_device_events
//   get_direction
//   get_display
//   get_double_buffered
//   get_events
//   get_focus_on_click
//   get_font_map
//   get_font_options
//   get_frame_clock
//   get_halign
//   get_has_tooltip
//   get_has_window
//   get_hexpand
//   get_hexpand_set
//   get_mapped
//   get_margin_bottom
//   get_margin_end
//   get_margin_left
//   get_margin_right
//   get_margin_start
//   get_margin_top
//   get_modifier_mask
//   get_modifier_style
//   get_name
//   get_no_show_all
//   get_opacity
//   get_pango_context
//   get_parent
//   get_parent_window
//   get_path
//   get_pointer
//   get_preferred_height
//   get_preferred_height_and_baseline_for_width
//   get_preferred_height_for_width
//   get_preferred_size
//   get_preferred_width
//   get_preferred_width_for_height
//   get_realized
//   get_receives_default
//   get_request_mode
//   get_requisition
//   get_root_window
//   get_scale_factor
//   get_screen
//   get_sensitive
//   get_settings
//   get_size_request
//   get_state
//   get_state_flags
//   get_style
//   get_style_context
//   get_support_multidevice
//   get_template_child
//   get_tooltip_markup
//   get_tooltip_text
//   get_tooltip_window
//   get_toplevel
//   get_valign
//   get_valign_with_baseline
//   get_vexpand
//   get_vexpand_set
//   get_visible
//   get_visual
//   get_window
//   grab_add
//   grab_default
//   grab_focus
//   grab_remove
//   has_default
//   has_focus
//   has_grab
//   has_rc_style
//   has_screen
//   has_visible_focus
//   hide
//   hide_on_delete
//   in_destruction
//   init_template
//   input_shape_combine_region
//   insert_action_group
//   intersect
//   is_ancestor
//   is_composited
//   is_drawable
//   is_focus
//   is_sensitive
//   is_toplevel
//   is_visible
//   keynav_failed
//   list_accel_closures
//   list_action_prefixes
//   list_mnemonic_labels
//   map
//   mnemonic_activate
//   modify_base
//   modify_bg
//   modify_cursor
//   modify_fg
//   modify_font
//   modify_style
//   modify_text
//   override_background_color
//   override_color
//   override_cursor
//   override_font
//   override_symbolic_color
//   path
//   queue_allocate
//   queue_compute_expand
//   queue_draw
//   queue_draw_area
//   queue_draw_region
//   queue_resize
//   queue_resize_no_redraw
//   realize
//   region_intersect
//   register_window
//   remove_accelerator
//   remove_mnemonic_label
//   remove_tick_callback
//   render_icon
//   render_icon_pixbuf
//   reparent
//   reset_rc_styles
//   reset_style
//   send_expose
//   send_focus_change
//   set_accel_path
//   set_allocation
//   set_app_paintable
//   set_can_default
//   set_can_focus
//   set_child_visible
//   set_clip
//   set_composite_name
//   set_device_enabled
//   set_device_events
//   set_direction
//   set_double_buffered
//   set_events
//   set_focus_on_click
//   set_font_map
//   set_font_options
//   set_halign
//   set_has_tooltip
//   set_has_window
//   set_hexpand
//   set_hexpand_set
//   set_mapped
//   set_margin_bottom
//   set_margin_end
//   set_margin_left
//   set_margin_right
//   set_margin_start
//   set_margin_top
//   set_name
//   set_no_show_all
//   set_opacity
//   set_parent
//   set_parent_window
//   set_realized
//   set_receives_default
//   set_redraw_on_allocate
//   set_sensitive
//   set_size_request
//   set_state
//   set_state_flags
//   set_style
//   set_support_multidevice
//   set_tooltip_markup
//   set_tooltip_text
//   set_tooltip_window
//   set_valign
//   set_vexpand
//   set_vexpand_set
//   set_visible
//   set_visual
//   set_window
//   shape_combine_region
//   show
//   show_all
//   show_now
//   size_allocate
//   size_allocate_with_baseline
//   size_request
//   style_attach
//   style_get
//   style_get_property
//   style_get_valist
//   thaw_child_notify
//   translate_coordinates
//   trigger_tooltip_query
//   unmap
//   unparent
//   unrealize
//   unregister_window
//   unset_state_flags
package org.gnome.gtk

import gtk3.*
import kotlinx.cinterop.CPointer
import kotlinx.cinterop.reinterpret
import kotlinx.cinterop.toKString
import org.gnome.glib.gobject.InitiallyUnowned

public typealias Widget = CPointer<GtkWidget>

public val Widget.asInitiallyUnowned: InitiallyUnowned
  get() = reinterpret()

///////////////////////////////////////////////////////////////////////////
// Public API (not generated)
///////////////////////////////////////////////////////////////////////////

var Widget.name
  get() = gtk_widget_get_name(this)?.toKString().orEmpty()
  set(value) = gtk_widget_set_name(this, value)

fun Widget.showAll() = gtk_widget_show_all(this)

fun Widget.destroy() = gtk_widget_destroy(this)
